package services

import (
	"bytes"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

var insecureHTTPClient = &http.Client{
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	},
}

type ArgoCDClient struct {
	ServerURL string
	Token     string
}

func NewArgoCDClient(url, token string) *ArgoCDClient {
	return &ArgoCDClient{ServerURL: url, Token: token}
}

func (c *ArgoCDClient) request(method, path string, body io.Reader) (*http.Response, error) {
	url := fmt.Sprintf("%s/api/v1/%s", c.ServerURL, path)
	req, err := http.NewRequest(method, url, body)
	if err != nil {
		return nil, err
	}
	req.Header.Add("Authorization", "Bearer "+c.Token)
	req.Header.Add("Content-Type", "application/json")
	return insecureHTTPClient.Do(req)
}

// AddRepository registers (or re-registers) a repository's credentials.
//
// upsert=true is what makes a second registration replace the first: ArgoCD
// answers a POST for a URL it already knows with 400 InvalidArgument ("existing
// repository spec is different; use upsert flag to force update"), not 409, so
// a retry keyed on 409 never ran and a rotated key was never picked up.
func (c *ArgoCDClient) AddRepository(repoURL, sshKey string) error {
	payload := map[string]interface{}{
		"repo":                  repoURL,
		"type":                  "git",
		"sshPrivateKey":         sshKey,
		"insecure":              true,
		"insecureIgnoreHostKey": true,
	}
	bodyBytes, _ := json.Marshal(payload)
	res, err := c.request("POST", "repositories?upsert=true", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 {
		resBody, _ := io.ReadAll(res.Body)
		return fmt.Errorf("register repository: HTTP %d: %s", res.StatusCode, strings.TrimSpace(string(resBody)))
	}
	return nil
}

func (c *ArgoCDClient) CreateProject(projectName string) error {
	payload := map[string]interface{}{
		"project": map[string]interface{}{
			"metadata": map[string]interface{}{
				"name": projectName,
			},
			"spec": map[string]interface{}{
				"description": fmt.Sprintf("Project %s generated by KubeCommit", projectName),
				"sourceRepos": []string{"*"},
				"destinations": []map[string]interface{}{
					{
						"server":    "*",
						"namespace": "*",
					},
				},
				"clusterResourceWhitelist": []map[string]interface{}{
					{
						"group": "*",
						"kind":  "*",
					},
				},
				"namespaceResourceWhitelist": []map[string]interface{}{
					{
						"group": "*",
						"kind":  "*",
					},
				},
			},
		},
	}
	bodyBytes, _ := json.Marshal(payload)
	res, err := c.request("POST", "projects", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 && res.StatusCode != 409 {
		resBody, _ := io.ReadAll(res.Body)
		return fmt.Errorf("failed to create argocd project: %s", string(resBody))
	}
	return nil
}

// AppName is the name ArgoCD gives the Application for a repository. Kept
// exported so whoever deletes it later asks for the same name that was created.
func AppName(name string) string { return sanitizeK8sName(name) }

func sanitizeK8sName(name string) string {
	result := strings.ToLower(name)
	result = strings.ReplaceAll(result, "_", "-")
	return result
}

func (c *ArgoCDClient) CreateApplication(appName, repoURL, project, namespace, appPath, targetRevision string) error {
	appName = sanitizeK8sName(appName)
	if appPath == "" {
		appPath = "."
	}
	if targetRevision == "" {
		targetRevision = "HEAD"
	}
	if namespace == "" {
		namespace = "default"
	}
	if project == "" {
		project = "default"
	}
	payload := map[string]interface{}{
		"metadata": map[string]interface{}{
			"name":      appName,
			"namespace": "argocd",
		},
		"spec": map[string]interface{}{
			"project": project,
			"source": map[string]interface{}{
				"repoURL":        repoURL,
				"path":           appPath,
				"targetRevision": targetRevision,
			},
			"destination": map[string]interface{}{
				"server":    "https://kubernetes.default.svc",
				"namespace": namespace,
			},
			"syncPolicy": map[string]interface{}{
				"automated": map[string]interface{}{
					"prune":    true,
					"selfHeal": true,
				},
				"syncOptions": []string{"CreateNamespace=true"},
			},
		},
	}
	bodyBytes, _ := json.Marshal(payload)
	res, err := c.request("POST", "applications", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 && res.StatusCode != 409 {
		resBody, _ := io.ReadAll(res.Body)
		return fmt.Errorf("create application: HTTP %d: %s", res.StatusCode, strings.TrimSpace(string(resBody)))
	}
	return nil
}

func (c *ArgoCDClient) DeleteApplication(appName string) error {
	res, err := c.request("DELETE", "applications/"+url.PathEscape(appName)+"?cascade=true", nil)
	if err != nil {
		return err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 && res.StatusCode != 404 {
		body, _ := io.ReadAll(res.Body)
		return fmt.Errorf("argocd delete HTTP %d: %s", res.StatusCode, string(body))
	}
	return nil
}
