package services

import (
	"bytes"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

var insecureHTTPClient = &http.Client{
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	},
}

type ArgoCDClient struct {
	ServerURL string
	Token     string
}

func NewArgoCDClient(url, token string) *ArgoCDClient {
	return &ArgoCDClient{ServerURL: url, Token: token}
}

func (c *ArgoCDClient) request(method, path string, body io.Reader) (*http.Response, error) {
	url := fmt.Sprintf("%s/api/v1/%s", c.ServerURL, path)
	req, err := http.NewRequest(method, url, body)
	if err != nil {
		return nil, err
	}
	req.Header.Add("Authorization", "Bearer "+c.Token)
	req.Header.Add("Content-Type", "application/json")
	return insecureHTTPClient.Do(req)
}

func (c *ArgoCDClient) AddRepository(repoURL, sshKey string) error {
	payload := map[string]interface{}{
		"repo":                  repoURL,
		"type":                  "git",
		"sshPrivateKey":         sshKey,
		"insecure":              true,
		"insecureIgnoreHostKey": true,
	}
	bodyBytes, _ := json.Marshal(payload)
	res, err := c.request("POST", "repositories", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}
	defer res.Body.Close()

	if res.StatusCode == 409 {
		encoded := url.QueryEscape(repoURL)
		delRes, delErr := c.request("DELETE", "repositories/"+encoded, nil)
		if delErr == nil {
			delRes.Body.Close()
		}
		bodyBytes2, _ := json.Marshal(payload)
		res2, err2 := c.request("POST", "repositories", bytes.NewBuffer(bodyBytes2))
		if err2 != nil {
			return err2
		}
		defer res2.Body.Close()
		if res2.StatusCode >= 400 {
			resBody, _ := io.ReadAll(res2.Body)
			return fmt.Errorf("failed to add argocd repo: %s", string(resBody))
		}
		return nil
	}

	if res.StatusCode >= 400 {
		resBody, _ := io.ReadAll(res.Body)
		return fmt.Errorf("failed to add argocd repo: %s", string(resBody))
	}
	return nil
}

func (c *ArgoCDClient) CreateProject(projectName string) error {
	payload := map[string]interface{}{
		"project": map[string]interface{}{
			"metadata": map[string]interface{}{
				"name": projectName,
			},
			"spec": map[string]interface{}{
				"description": fmt.Sprintf("Project %s generated by KubeCommit", projectName),
				"sourceRepos": []string{"*"},
				"destinations": []map[string]interface{}{
					{
						"server":    "*",
						"namespace": "*",
					},
				},
				"clusterResourceWhitelist": []map[string]interface{}{
					{
						"group": "*",
						"kind":  "*",
					},
				},
				"namespaceResourceWhitelist": []map[string]interface{}{
					{
						"group": "*",
						"kind":  "*",
					},
				},
			},
		},
	}
	bodyBytes, _ := json.Marshal(payload)
	res, err := c.request("POST", "projects", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 && res.StatusCode != 409 {
		resBody, _ := io.ReadAll(res.Body)
		return fmt.Errorf("failed to create argocd project: %s", string(resBody))
	}
	return nil
}

func (c *ArgoCDClient) CreateApplication(appName, repoURL, project, appPath, targetRevision string) error {
	if appPath == "" {
		appPath = "manifests"
	}
	if targetRevision == "" {
		targetRevision = "HEAD"
	}
	payload := map[string]interface{}{
		"metadata": map[string]interface{}{
			"name":      appName,
			"namespace": "argocd",
		},
		"spec": map[string]interface{}{
			"project": project,
			"source": map[string]interface{}{
				"repoURL":        repoURL,
				"path":           appPath,
				"targetRevision": targetRevision,
			},
			"destination": map[string]interface{}{
				"server":    "https://kubernetes.default.svc",
				"namespace": "apis",
			},
			"syncPolicy": map[string]interface{}{
				"automated": map[string]interface{}{
					"prune":    true,
					"selfHeal": true,
				},
				"syncOptions": []string{"CreateNamespace=true"},
			},
		},
	}
	bodyBytes, _ := json.Marshal(payload)
	res, err := c.request("POST", "applications", bytes.NewBuffer(bodyBytes))
	if err != nil {
		return err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 && res.StatusCode != 409 {
		resBody, _ := io.ReadAll(res.Body)
		return fmt.Errorf("failed to create argocd app: %s", string(resBody))
	}
	return nil
}
